name: make fish_run_tests

on: [push, pull_request]

env:
  FISH_TEST_MAX_CONCURRENCY: "4"
  CMAKE_BUILD_PARALLEL_LEVEL: "4"

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    # # TODO not sure if these are needed
    # - name: Install Cygwin
    #   run: |
    #     set -x
    #     choco install cygwin --yes
    #     choco install cyg-get --yes
    # - name: Install required Cygwin packages
    #   run: |
    #     cyg-get make gcc-core git curl
    - name: Build project (Rust inside Cygwin)
      shell: C:\cygwin64\bin\bash.exe -l {0}
      run: |
        set -x
        # source ~/.cargo/env
        # cargo build --verbose
        pacman -S gcc mingw-w64-x86_64-rustup
        git fetch --unshallow
        git checkout d8e5821
        rustup component add rust-src --toolchain nightly-x86_64-pc-windows-gnu
        # cargo +nightly-x86_64-pc-windows-gnu build -Z build-std --target x86_64-pc-cygwin --bin fish
        cargo +nightly-x86_64-pc-windows-gnu install -Z build-std --target x86_64-pc-cygwin --path . --bin fish --debug
        fish -c 'ls >/dev/null'
        # target/debug/fish -c 'ls >/dev/null'
        # target/x86_64-pc-cygwin/debug/fish.exe -c 'ls >/dev/null'
        for f in $(seq 100)
        do
          echo $f
          if target/debug/fish -c 'ls >/dev/null' 2>&1 | grep select
          then
            break
          fi
        done
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
