name: testflow

on:
    workflow_dispatch:

jobs:
  staticbuilds-linux:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: test
      run: |
        echo Test
